version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    ports:
      - "9001:8000"
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    ports:
      - "9000:80"
    depends_on:
      - backend
    restart: unless-stopped 