version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    ports:
      - "9001:8000"
    environment:
      - ENVIRONMENT=production
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-this-in-production
      - JWT_ALGORITHM=HS256
      - CONVERSATION_SECRET_KEY=your-super-secret-conversation-key-change-this-in-production
      - CORS_ORIGINS=http://localhost:9000,http://localhost:5173,https://chattermate.chat
      - ENCRYPTION_KEY=RFQ4SzhyRTVYdGtsLUxsc25SaDB0QlZpbTdQRmlVRlpsZUlCaFRlU2Vxbz0=
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    ports:
      - "9000:80"
    environment:
      - VITE_API_URL=/api/v1
      - VITE_WS_URL=ws://localhost:9001
      - VITE_WIDGET_URL=http://localhost:9000
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped 